In [11]:
import numpy as np

In [21]:

ack = np.arange(10)

ind1 = np.where(ack > 5)[0]
ind2 = np.where(ack[ind1] < 9)[0]


In [25]:
ack[ind1][ind2]


array([6, 7, 8])

In [26]:
ack[ind1[ind2]]

array([6, 7, 8])

In [27]:
ack = np.arange(10)
ack[ind1][ind2] = 666
ack

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
ack = np.arange(10)
ack[ind1[ind2]] = 666
ack

array([  0,   1,   2,   3,   4,   5, 666, 666, 666,   9])

In [ ]:
# But there are other times where one might want to use ack[ind1][ind2] = something and it would
# work, e.g., if it was a nested list. 